-- 1
SELECT SNAME,SSEX,CLASS FROM STUDENT;
--2 
SELECT DISTINCT DEPART 
FROM TEACHER;

--4
SELECT *
FROM SCORE
WHERE DEGREE >= 60 AND DEGREE <= 80;

SELECT *
FROM SCORE
WHERE DEGREE BETWEEN 60 AND 80;


-- 5、 查询Score表中成绩为85，86或88的记录。--
SELECT *
FROM SCORE
WHERE DEGREE = 85 OR DEGREE = 86 OR DEGREE = 88;


SELECT *
FROM SCORE
WHERE DEGREE = 85 
UNION SELECT *
FROM SCORE
WHERE DEGREE = 86 
UNION SELECT *
FROM SCORE
WHERE DEGREE = 88;

-- 6、 查询Student表中“95031”班或性别为“女”的同学记录。--
SELECT * 
FROM STUDENT 
WHERE SSEX = '女' OR CLASS = '95031';


-- 7、 以Class降序查询Student表的所有记录。--
SELECT *
FROM STUDENT
ORDER BY CLASS DESC;

-- 8、 以Cno升序、Degree降序查询Score表的所有记录。--
SELECT *
FROM SCORE
ORDER BY CNO ASC, DEGREE DESC;

-- 9、 查询“95031”班的学生人数。--
SELECT COUNT(*)
FROM STUDENT
WHERE CLASS = '95031';

-- 10、查询Score表中的最高分的学生学号和课程号。--
SELECT SNO, CNO
FROM SCORE
WHERE DEGREE = (
    SELECT MAX(DEGREE)
    FROM SCORE
);


-- 11、查询‘3-105’号课程的平均分。--
SELECT AVG(DEGREE)
FROM SCORE
WHERE CNO = '3-105';

 
-- 12、查询Score表中至少有5名学生选修的并以3开头的课程的平均分数。--
SELECT AVG(DEGREE)
FROM SCORE
GROUP BY CNO
HAVING COUNT(*)>=5 AND CNO LIKE '3%';

SELECT AVG(DEGREE) FROM SCORE
WHERE CNO LIKE'3%' 
GROUP BY CNO
HAVING COUNT(*)>=5;

--Which is better?
-- 13、查询最低分大于70，最高分小于90的Sno列。--
SELECT SNO
FROM SCORE
GROUP BY SNO 
HAVING MIN(DEGREE)>70 AND MAX(DEGREE)<90;

-- 14、查询所有学生的Sname、Cno和Degree列。--
SELECT SNAME,CNO,DEGREE
FROM STUDENT NATURAL JOIN SCORE;

SELECT SNAME,CNO,DEGREE 
FROM STUDENT,SCORE
WHERE STUDENT.SNO=SCORE.SNO;

 
-- 16、查询所有学生的Sname、Cname和Degree列。--
SELECT SNAME,CNAME,DEGREE
FROM STUDENT NATURAL JOIN SCORE NATURAL JOIN COURSE;

-- 17、查询“95033”班所选课程的平均分。--
SELECT AVG(DEGREE)
FROM STUDENT NATURAL JOIN SCORE
WHERE CLASS = 95033;

-- ALSO OK??
SELECT AVG(DEGREE)
FROM STUDENT NATURAL JOIN SCORE
WHERE CLASS = 95033
GROUP BY CLASS;

-- 19、查询选修“3-105”课程的成绩高于“109”号同学成绩的所有同学的记录。--
SELECT *
FROM STUDENT
WHERE SNO IN ( -- NOTE THE IN INSTEAD OF = HERE 
    SELECT SNO
    FROM SCORE
    WHERE CNO = '3-105' AND DEGREE>(
        SELECT DEGREE
        FROM SCORE
        WHERE SNO = 109 AND CNO = '3-105'
    )
);
-- 20、查询score中选学一门以上课程的同学中分数为非最高分成绩的记录。--
SELECT * 
FROM SCORE 
WHERE DEGREE < (SELECT MAX(DEGREE) FROM SCORE) 
    AND SNO IN (SELECT SNO FROM SCORE
GROUP BY SNO
HAVING COUNT(*) > 1);

-- 21、查询成绩高于学号为“109”、课程号为“3-105”的成绩的所有记录。--
SELECT *
FROM SCORE
WHERE CNO = '3-105' AND DEGREE > (SELECT DEGREE 
FROM SCORE
WHERE SNO =109 AND CNO= '3-105');

SELECT B.* 
FROM SCORE A, SCORE B -- also ok to us a join b
WHERE A.SNO = 109 AND A.CNO='3-105' AND B.CNO = '3-105' AND B.DEGREE > A.DEGREE;

-- 23、查询“张旭“教师任课的学生成绩。--
SELECT DEGREE
FROM SCORE NATURAL JOIN COURSE NATURAL JOIN TEACHER
WHERE TNAME = '张旭';


-- 24、查询选修某课程的同学人数多于5人的教师姓名。

SELECT TNAME 
FROM SCORE NATURAL JOIN COURSE NATURAL JOIN TEACHER
GROUP BY CNO
HAVING COUNT(*)>5;

-- 25、查询95033班和95031班全体学生的记录。--
SELECT * 
FROM STUDENT
WHERE CLASS IN ('95033','95031');

-- 26、查询存在有85分以上成绩的课程Cno.--
SELECT DISTINCT CNO
FROM SCORE
WHERE DEGREE > 85;

-- 27、查询出“计算机系“教师所教课程的成绩表。--
SELECT DEGREE
FROM SCORE NATURAL JOIN COURSE NATURAL JOIN TEACHER
WHERE DEPART = '计算机系';

-- -- 28、查询“计算机系”与“电子工程系“不同职称的教师的Tname和Prof。--
-- SELECT TNAME, PROF 
-- FROM TEACHER
-- WHERE DEPART IN('计算机系','电子工程系');

-- 29、查询选修编号为“3-105“课程且成绩至少高于选修编号为“3-245”的同学的Cno、Sno和Degree,并按Degree从高到低次序排序。--
SELECT CNO,SNO,DEGREE
FROM SCORE
WHERE CNO = '3-105' AND DEGREE> ANY(SELECT DEGREE FROM SCORE WHERE CNO ='3-245')
ORDER BY DEGREE DESC;

-- 30、查询选修编号为“3-105”且成绩高于选修编号为“3-245”课程的同学的Cno、Sno和Degree.--
SELECT CNO,SNO,DEGREE
FROM SCORE
WHERE CNO = '3-105' AND DEGREE> ALL(SELECT DEGREE FROM SCORE WHERE CNO ='3-245');

-- NOTICE THE DIFFERENCE BETWEEEN > ALL AND > ANY


-- 31、查询所有教师和同学的name、sex和birthday.--
SELECT SNAME AS NAME,SSEX AS SEX,SBIRTHDAY AS BIRTHDAY
FROM STUDENT
UNION
SELECT TNAME AS NAME,TSEX AS SEX,TBIRTHDAY AS BIRTHDAY
FROM TEACHER;

-- 33、查询成绩比该课程平均成绩低的同学的成绩表。--
SELECT DEGREE
FROM SCORE A
WHERE DEGREE < (
    SELECT AVG(DEGREE)
    FROM SCORE B
    WHERE A.CNO = B.CNO 
);

-- 35  查询所有未讲课的教师的Tname和Depart.--
SELECT TNAME, DEPART
FROM TEACHER
WHERE TNO NOT IN (
    SELECT TNO 
    FROM COURSE
);

-- SELECT TNAME, DEPART
-- FROM TEACHER
-- WHERE TNO IN(SELECT TNO FROM TEACHER MINUS SELECT TNO FROM COURSE);

-- 42、查询最高分同学的Sno、Cno和Degree列。--
SELECT SNO, CNO, DEGREE
FROM SCORE
WHERE DEGREE = (
    SELECT MAX(DEGREE) 
    FROM SCORE
);
