-- show 
SELECT * FROM STUDENT;
SELECT * FROM INSTRUCTOR;
SELECT * FROM PROJECT;
SELECT * FROM PREFER;
SELECT * FROM WORKS_ON;

SELECT STU_ID, PREFERENCE_FULFILLED FROM STUDENT;
UPDATE PREFER SET PROJ_5 = 00018 WHERE STU_ID ='S0010';

SELECT COUNT(*),STU_ID
FROM PREFER 
GROUP BY STU_ID;

-- test
INSERT INTO PROJECT VALUES(00021,'Quantitative zoology','test');
SELECT * FROM PREFER;


SELECT PROJ_ID, STUDENT.EMAIL AS STUDENT_EMAIL, INSTRUCTOR.EMAIL AS INSTRUCTOR_EMAIL
FROM STUDENT NATURAL JOIN WORKS_ON
             NATURAL JOIN PROJECT 
             LEFT JOIN INSTRUCTOR ON PROJECT.INST_ID = INSTRUCTOR.INST_ID;

UPDATE PREFER SET PROJ_1 = NULL WHERE STU_ID = 'S0001';

SELECT * FROM STUDENT WHERE STU_ID = 'S0001'

SELECT COUNT(DISTINCT INST_ID)
FROM (
SELECT INST_ID
from PREFER JOIN PROJECT ON PREFER.PROJ_1 = PROJECT.PROJ_ID
WHERE STU_ID = :NEW.STU_ID UNION 
SELECT INST_ID
from PREFER JOIN PROJECT ON PREFER.PROJ_2 = PROJECT.PROJ_ID
WHERE STU_ID = :NEW.STU_ID UNION 
SELECT INST_ID
from PREFER JOIN PROJECT ON PREFER.PROJ_3 = PROJECT.PROJ_ID
WHERE STU_ID = :NEW.STU_ID UNION 
SELECT INST_ID
from PREFER JOIN PROJECT ON PREFER.PROJ_4 = PROJECT.PROJ_ID
WHERE STU_ID = :NEW.STU_ID UNION 
SELECT INST_ID
from PREFER JOIN PROJECT ON PREFER.PROJ_5 = PROJECT.PROJ_ID
WHERE STU_ID = :NEW.STU_ID);


SELECT *
from PREFER JOIN PROJECT ON PREFER.PROJ_1 = PROJECT.PROJ_ID;



-- This trigger tests if a student indicated 5 valid preference.
CREATE OR REPLACE TRIGGER PREFERENCE_FULFILLMENT_CHECK
AFTER INSERT OR UPDATE OF PROJ_1,PROJ_2,PROJ_3,PROJ_4,PROJ_5
ON PREFER
FOR EACH ROW
DECLARE 
    DISTINCT_INST NUMBER;
BEGIN
    IF :NEW.PROJ_1 IS NOT NULL AND :NEW.PROJ_2 IS NOT NULL AND :NEW.PROJ_3 IS NOT NULL AND :NEW.PROJ_4 IS NOT NULL AND :NEW.PROJ_5 IS NOT NULL THEN
        SELECT COUNT(DISTINCT INST_ID) INTO DISTINCT_INST
            FROM (
            SELECT INST_ID
            FROM  PROJECT 
            WHERE :NEW.PROJ_1 = PROJ_ID UNION 
            SELECT INST_ID
            from  PROJECT 
            WHERE :NEW.PROJ_2 = PROJ_ID UNION 
            SELECT INST_ID
            from  PROJECT 
            WHERE :NEW.PROJ_3 = PROJ_ID UNION 
            SELECT INST_ID 
            from  PROJECT 
            WHERE :NEW.PROJ_4 = PROJ_ID UNION 
            SELECT INST_ID
            from  PROJECT 
            WHERE :NEW.PROJ_5 = PROJ_ID);
        IF DISTINCT_INST <> 5 THEN 
            RAISE_APPLICATION_ERROR(-20000,'Duplicate instructors detected!');
        END IF;
        UPDATE STUDENT
        SET PREFERENCE_FULFILLED = 1
        WHERE STU_ID = :NEW.STU_ID;
    ELSE
        UPDATE STUDENT
        SET PREFERENCE_FULFILLED = 0
        WHERE STU_ID = :NEW.STU_ID;
    END IF;
END;
/


CREATE OR REPLACE TRIGGER DUPLICATE_INSTRUCTORS
AFTER UPDATE OF PREFERENCE_FULFILLED
ON STUDENT
FOR EACH ROW
DECLARE 
    PRAGMA AUTONOMOUS_TRANSACTION;
    I NUMBER;
BEGIN
    SELECT COUNT(DISTINCT INST_ID) INTO I
        FROM (
        SELECT INST_ID
        from PREFER JOIN PROJECT ON PREFER.PROJ_1 = PROJECT.PROJ_ID
        WHERE STU_ID = :NEW.STU_ID UNION 
        SELECT INST_ID
        from PREFER JOIN PROJECT ON PREFER.PROJ_2 = PROJECT.PROJ_ID
        WHERE STU_ID = :NEW.STU_ID UNION 
        SELECT INST_ID
        from PREFER JOIN PROJECT ON PREFER.PROJ_3 = PROJECT.PROJ_ID
        WHERE STU_ID = :NEW.STU_ID UNION 
        SELECT INST_ID
        from PREFER JOIN PROJECT ON PREFER.PROJ_4 = PROJECT.PROJ_ID
        WHERE STU_ID = :NEW.STU_ID UNION 
        SELECT INST_ID
        from PREFER JOIN PROJECT ON PREFER.PROJ_5 = PROJECT.PROJ_ID
        WHERE STU_ID = :NEW.STU_ID);
    IF I < 5 THEN 
        RAISE_APPLICATION_ERROR(-20000,'Duplicate instructors!');
    END IF;
    COMMIT; 
END;
/


SELECT COUNT(DISTINCT INST_ID) INTO I
            FROM (
            SELECT INST_ID
            FROM  PROJECT 
            WHERE STU_ID = 'S0005' AND 1= PROJ_ID UNION 
            SELECT INST_ID
            from  PROJECT 
            WHERE STU_ID = 'S0005' AND 2 = PROJ_ID UNION 
            SELECT INST_ID
            from  PROJECT 
            WHERE STU_ID = 'S0005' AND 3 = PROJ_ID UNION 
            SELECT INST_ID 
            from  PROJECT 
            WHERE STU_ID = 'S0005' AND 4 = PROJ_ID UNION 
            SELECT INST_ID
            from  PROJECT 
            WHERE STU_ID = 'S0005' AND 5 = PROJ_ID);